class AppLocalizations {
  static String currentLanguage = 'en';
  
  static final Map<String, Map<String, String>> _translations = {
    'en': {
      // Login
      'enter_phone': 'Enter your phone number',
      'otp_description': 'AURA will send you a one-time password to verify your number.',
      'request_otp': 'Request OTP',
      'phone_hint': 'Phone number',
      'invalid_phone': 'Invalid phone number for this country',
      'hide_number_info': 'You can hide your phone number after signup. Other users will only see your username.',
      'back_to_terms': 'Back to Terms',
      
      // OTP
      'verify_number': 'Verify your number',
      'enter_code_sent_to': 'Enter the 6-digit code sent to',
      'resend_code_in': 'Resend code in',
      'resend_code': 'Resend Code',
      'verify': 'Verify',
      'invalid_otp': 'Invalid OTP. Please try again.',
      
      // Setup
      'setup_profile': 'Set up your profile',
      'setup_description': 'Choose how others will see you on AURA. You can always change this later.',
      'display_name': 'Display Name',
      'display_name_hint': 'How you want to be known',
      'username': 'Username',
      'username_hint': 'Your unique @username',
      'bio': 'Bio',
      'bio_hint': 'Tell people about yourself',
      'verification': 'Verification',
      'verification_desc': 'Verified badges are available for public figures, brands, and businesses. Apply after setup for \$4.99.',
      'complete_setup': 'Complete Setup',
      'tap_add_photo': 'Tap to add photo',
      'please_enter_name': 'Please enter your display name',
      'please_enter_username': 'Please enter a valid username',
      'username_taken': 'Username is already taken',
      'username_short': 'Username must be at least 3 characters',
      'username_invalid': 'Only letters, numbers, and underscores allowed',
      'camera': 'Camera',
      'gallery': 'Gallery',
      
      // Main
      'chats': 'CHATS',
      'status': 'STATUS',
      'calls': 'CALLS',
      'no_chats': 'No chats yet',
      'start_conversation': 'Start a new conversation!',
      'call_history': 'Call history',
      'status_updates': 'Status updates',
      'my_status': 'My Status',
      'tap_add_status': 'Tap to add status',
      'recent_updates': 'RECENT UPDATES',
      'no_status_updates': 'No status updates',
      'tap_share_first_status': 'Tap + to share your first status',
      'post': 'Post',

      // FAB options
      'new_chat': 'New Chat',
      'new_group': 'New Group',
      'new_channel': 'New Channel',
      'video': 'Video',
      'text_status': 'Text Status',
      'new_call': 'New Call',
      'video_call': 'Video Call',
      'share_code': 'Share this code with the person you want to call:',
      
      // Menu
      'settings': 'Settings',
      'profile': 'Profile',
      'sign_out': 'Sign Out',
      
      // Settings
      'account': 'Account',
      'security_change_number': 'Security, change number',
      'privacy': 'Privacy',
      'block_contacts': 'Block contacts, disappearing messages',
      'avatar': 'Avatar',
      'create_edit_photo': 'Create, edit, profile photo',
      'theme_wallpapers': 'Theme, wallpapers, chat history',
      'notifications': 'Notifications',
      'message_group_call_tones': 'Message, group & call tones',
      'storage_and_data': 'Storage and Data',
      'network_usage': 'Network usage, auto-download',
      'app_language': 'App Language',
      'english_default': 'English (device default)',
      'help': 'Help',
      'help_center': 'Help center, contact us, privacy policy',
      'invite_friends': 'Invite Friends',
      'log_out': 'Log Out',
      'version': 'AURA Chat v1.0.0',
      'select_language': 'Select Language',
      'cancel': 'Cancel',
    },
    
    // Spanish
    'es': {
      'enter_phone': 'Ingresa tu número de teléfono',
      'otp_description': 'AURA te enviará una contraseña de un solo uso para verificar tu número.',
      'request_otp': 'Solicitar OTP',
      'phone_hint': 'Número de teléfono',
      'invalid_phone': 'Número de teléfono inválido para este país',
      'hide_number_info': 'Puedes ocultar tu número después del registro. Otros usuarios solo verán tu nombre de usuario.',
      'back_to_terms': 'Volver a Términos',
      
      'verify_number': 'Verifica tu número',
      'enter_code_sent_to': 'Ingresa el código de 6 dígitos enviado a',
      'resend_code_in': 'Reenviar código en',
      'resend_code': 'Reenviar Código',
      'verify': 'Verificar',
      'invalid_otp': 'OTP inválido. Inténtalo de nuevo.',
      
      'setup_profile': 'Configura tu perfil',
      'setup_description': 'Elige cómo te verán otros en AURA. Siempre puedes cambiarlo después.',
      'display_name': 'Nombre para mostrar',
      'display_name_hint': 'Cómo quieres ser conocido',
      'username': 'Nombre de usuario',
      'username_hint': 'Tu @usuario único',
      'bio': 'Biografía',
      'bio_hint': 'Cuéntales a las personas sobre ti',
      'verification': 'Verificación',
      'verification_desc': 'Las insignias verificadas están disponibles para figuras públicas, marcas y negocios. Aplica después del registro por \$4.99.',
      'complete_setup': 'Completar Configuración',
      'tap_add_photo': 'Toca para agregar foto',
      'please_enter_name': 'Por favor ingresa tu nombre',
      'please_enter_username': 'Por favor ingresa un nombre de usuario válido',
      'username_taken': 'El nombre de usuario ya está en uso',
      'username_short': 'El nombre de usuario debe tener al menos 3 caracteres',
      'username_invalid': 'Solo letras, números y guiones bajos permitidos',
      'camera': 'Cámara',
      'gallery': 'Galería',
      
      'chats': 'CHATS',
      'status': 'ESTADOS',
      'calls': 'LLAMADAS',
      'no_chats': 'Aún no hay chats',
      'start_conversation': '¡Inicia una nueva conversación!',
      'call_history': 'Historial de llamadas',
      'status_updates': 'Actualizaciones de estado',
      
      'new_chat': 'Nuevo Chat',
      'new_group': 'Nuevo Grupo',
      'new_channel': 'Nuevo Canal',
      'video': 'Video',
      'text_status': 'Estado de Texto',
      'new_call': 'Nueva Llamada',
      'video_call': 'Videollamada',
      'share_code': 'Comparte este código con la persona a la que quieres llamar:',
      
      'settings': 'Configuración',
      'profile': 'Perfil',
      'sign_out': 'Cerrar Sesión',
      
      'account': 'Cuenta',
      'security_change_number': 'Seguridad, cambiar número',
      'privacy': 'Privacidad',
      'block_contacts': 'Bloquear contactos, mensajes temporales',
      'avatar': 'Avatar',
      'create_edit_photo': 'Crear, editar, foto de perfil',
      'theme_wallpapers': 'Tema, fondos, historial',
      'notifications': 'Notificaciones',
      'message_group_call_tones': 'Tono de mensajes, grupos y llamadas',
      'storage_and_data': 'Almacenamiento y Datos',
      'network_usage': 'Uso de red, descarga automática',
      'app_language': 'Idioma',
      'english_default': 'Español',
      'help': 'Ayuda',
      'help_center': 'Centro de ayuda, contacto, política',
      'invite_friends': 'Invitar Amigos',
      'log_out': 'Cerrar Sesión',
      'version': 'AURA Chat v1.0.0',
      'select_language': 'Seleccionar Idioma',
      'cancel': 'Cancelar',
    },
    
    // French
    'fr': {
      'enter_phone': 'Entrez votre numéro de téléphone',
      'otp_description': 'AURA vous enverra un mot de passe à usage unique pour vérifier votre numéro.',
      'request_otp': 'Demander OTP',
      'phone_hint': 'Numéro de téléphone',
      'invalid_phone': 'Numéro de téléphone invalide pour ce pays',
      'hide_number_info': 'Vous pouvez masquer votre numéro après l\'inscription. Les autres utilisateurs ne verront que votre nom d\'utilisateur.',
      'back_to_terms': 'Retour aux Conditions',
      
      'verify_number': 'Vérifiez votre numéro',
      'enter_code_sent_to': 'Entrez le code à 6 chiffres envoyé à',
      'resend_code_in': 'Renvoyer le code dans',
      'resend_code': 'Renvoyer le Code',
      'verify': 'Vérifier',
      'invalid_otp': 'OTP invalide. Veuillez réessayer.',
      
      'setup_profile': 'Configurez votre profil',
      'setup_description': 'Choisissez comment les autres vous verront sur AURA. Vous pouvez toujours changer cela plus tard.',
      'display_name': 'Nom d\'affichage',
      'display_name_hint': 'Comment vous voulez être connu',
      'username': 'Nom d\'utilisateur',
      'username_hint': 'Votre @utilisateur unique',
      'bio': 'Bio',
      'bio_hint': 'Parlez aux gens de vous',
      'verification': 'Vérification',
      'verification_desc': 'Les badges vérifiés sont disponibles pour les personnalités publiques, marques et entreprises. Postulez après l\'inscription pour \$4.99.',
      'complete_setup': 'Terminer la Configuration',
      'tap_add_photo': 'Appuyez pour ajouter une photo',
      'please_enter_name': 'Veuillez entrer votre nom',
      'please_enter_username': 'Veuillez entrer un nom d\'utilisateur valide',
      'username_taken': 'Ce nom d\'utilisateur est déjà pris',
      'username_short': 'Le nom d\'utilisateur doit avoir au moins 3 caractères',
      'username_invalid': 'Seuls les lettres, chiffres et underscores sont autorisés',
      'camera': 'Caméra',
      'gallery': 'Galerie',
      
      'chats': 'DISCUSSIONS',
      'status': 'STATUTS',
      'calls': 'APPELS',
      'no_chats': 'Pas encore de discussions',
      'start_conversation': 'Commencez une nouvelle conversation !',
      'call_history': 'Historique d\'appels',
      'status_updates': 'Mises à jour de statut',
      
      'new_chat': 'Nouvelle Discussion',
      'new_group': 'Nouveau Groupe',
      'new_channel': 'Nouveau Canal',
      'video': 'Vidéo',
      'text_status': 'Statut Texte',
      'new_call': 'Nouvel Appel',
      'video_call': 'Appel Vidéo',
      'share_code': 'Partagez ce code avec la personne que vous voulez appeler :',
      
      'settings': 'Paramètres',
      'profile': 'Profil',
      'sign_out': 'Déconnexion',
      
      'account': 'Compte',
      'security_change_number': 'Sécurité, changer numéro',
      'privacy': 'Confidentialité',
      'block_contacts': 'Bloquer contacts, messages éphémères',
      'avatar': 'Avatar',
      'create_edit_photo': 'Créer, modifier, photo de profil',
      'theme_wallpapers': 'Thème, fonds, historique',
      'notifications': 'Notifications',
      'message_group_call_tones': 'Sonneries messages, groupes, appels',
      'storage_and_data': 'Stockage et Données',
      'network_usage': 'Usage réseau, téléchargement auto',
      'app_language': 'Langue',
      'english_default': 'Français',
      'help': 'Aide',
      'help_center': 'Centre aide, contact, politique',
      'invite_friends': 'Inviter des Amis',
      'log_out': 'Déconnexion',
      'version': 'AURA Chat v1.0.0',
      'select_language': 'Choisir la Langue',
      'cancel': 'Annuler',
    },
    
    // Hausa
    'ha': {
      'enter_phone': 'Shigar da lambar wayarka',
      'otp_description': 'AURA zai aika maka da kalmar sirri don tabbatar da lambar ka.',
      'request_otp': 'Nemi OTP',
      'phone_hint': 'Lambar waya',
      'invalid_phone': 'Lambar waya ba daidai ba ce don wannan ƙasa',
      'hide_number_info': 'Kana iya ɓoye lambar wayarka bayan rajista. Sauran masu amfani za su ga sunan mai amfani ka kawai.',
      'back_to_terms': 'Koma zuwa Sharuɗɗa',
      
      'verify_number': 'Tabbatar da lambar ka',
      'enter_code_sent_to': 'Shigar da lambar 6-zuwa da aka aika zuwa',
      'resend_code_in': 'Sake aika lambar a cikin',
      'resend_code': 'Sake Aika Lambar',
      'verify': 'Tabbatar',
      'invalid_otp': 'OTP ba daidai ba. Sake gwadawa.',
      
      'setup_profile': 'Saita bayaninka',
      'setup_description': 'Zaɓi yadda wasu za su ganin ka a AURA. Kana iya canzawa wannan daga baya.',
      'display_name': 'Sunan da za a nuna',
      'display_name_hint': 'Yadda kake so a san ka',
      'username': 'Sunan mai amfani',
      'username_hint': 'Sunanka na musamman @mai amfani',
      'bio': 'Tarihi',
      'bio_hint': 'Gaya wa mutane game da kai',
      'verification': 'Tabbatarwa',
      'verification_desc': 'Alamun tabbatarwa suna samuwa ga manyan mutane, kamfanoni da kasuwanci. Nemi bayan rajista don \$4.99.',
      'complete_setup': 'Kammala Saita',
      'tap_add_photo': 'Taɓa don ƙara hoto',
      'please_enter_name': 'Da fatan za a shigar da sunanka',
      'please_enter_username': 'Da fatan za a shigar da sunan mai amfani mai kyau',
      'username_taken': 'An riga an ɗauki wannan sunan mai amfani',
      'username_short': 'Dole sunan mai amfani ya kasance haruffa 3 ko fiye',
      'username_invalid': 'Haruffa, lambobi da karkashin layi kadai aka yarda',
      'camera': 'Kyamara',
      'gallery': 'Galeri',
      
      'chats': 'SADARWA',
      'status': 'MATSAYI',
      'calls': 'KIRA',
      'no_chats': 'Babu sadarwa tukuna',
      'start_conversation': 'Fara sabon tattaunawa!',
      'call_history': 'Tarihin kira',
      'status_updates': 'Sabuntawar matsayi',
      
      'new_chat': 'Sabuwar Sadarwa',
      'new_group': 'Sabuwar Rukuni',
      'new_channel': 'Sabon Tashar',
      'video': 'Bidiyo',
      'text_status': 'Matsayin Rubutu',
      'new_call': 'Sabuwar Kira',
      'video_call': 'Kiran Bidiyo',
      'share_code': 'Raba wannan lambar da mutumin da kake son kira:',
      
      'settings': 'Saituna',
      'profile': 'Bayani',
      'sign_out': 'Fita',
      
      'account': 'Asusu',
      'security_change_number': 'Tsaro, canza lamba',
      'privacy': 'Sirri',
      'block_contacts': 'Toshe lambobi, saƙonnin da suke ɓacewa',
      'avatar': 'Hoton fuska',
      'create_edit_photo': 'Ƙirƙira, gyara, hoton bayani',
      'theme_wallpapers': 'Jigo, fentin fuska, tarihi',
      'notifications': 'Sanarwa',
      'message_group_call_tones': 'Sautin saƙo, ƙungiya & kira',
      'storage_and_data': 'Majiya da Bayanai',
      'network_usage': 'Amfani da hanyar sadarwa, sauke kai tsaye',
      'app_language': 'Yaren App',
      'english_default': 'Hausa',
      'help': 'Taimako',
      'help_center': 'Cibiyar taimako, tuntuɓa, manufofi',
      'invite_friends': 'Gayyato Abokai',
      'log_out': 'Fita',
      'version': 'AURA Chat v1.0.0',
      'select_language': 'Zaɓi Harshe',
      'cancel': 'Soke',
    },
    
    // Yoruba
    'yo': {
      'enter_phone': 'Tẹ nọ́mbà fóònù rẹ',
      'otp_description': 'AURA yóò rán ọ́ ní ọ̀rọ̀ aṣínà kan láti fi hàn pé nọ́mbà rẹ tó tọ́.',
      'request_otp': 'Béèrè fún OTP',
      'phone_hint': 'Nọ́mbà fóònù',
      'invalid_phone': 'Nọ́mbà fóònù tí kò tọ́ fún orílẹ̀-èdè yìí',
      'hide_number_info': 'O lè fi nọ́mbà rẹ pamọ́ lẹ́yìn ìforígílé. Àwọn aṣàmúlò mìíràn yóò rí orúkọ aṣàmúlò rẹ nìkan.',
      'back_to_terms': 'Padà sí Ìlànà',
      
      'verify_number': 'Fi hàn pé nọ́mbà rẹ tó tọ́',
      'enter_code_sent_to': 'Tẹ kóòdù 6-nọ́mbà tí a rán sí',
      'resend_code_in': 'Tún rán kóòdù nínú',
      'resend_code': 'Tún Rán Kóòdù',
      'verify': 'Fi Hàn',
      'invalid_otp': 'OTP tí kò tọ́. Jọ̀wọ́ gbìyànjú lẹ́ẹ̀kan sí i.',
      
      'setup_profile': 'Ṣètò àwòrán rẹ',
      'setup_description': 'Yan bí àwọn ènìyàn yóò rí ọ́ lórí AURA. O lè yí èyí padà nígbà mìíràn.',
      'display_name': 'Orúkọ tí Yóò Hàn',
      'display_name_hint': 'Bí o fẹ́ kí a mọ̀ ọ́',
      'username': 'Orúkọ Aṣàmúlò',
      'username_hint': 'Orúkọ aṣàmúlò rẹ tó yàtọ̀ @',
      'bio': 'Ìtàn',
      'bio_hint': 'Sọ fún àwọn ènìyàn nípa rẹ',
      'verification': 'Ìfihàn',
      'verification_desc': 'Àmì ìfihàn wà fún àwọn olókìkí, àwọn àmì-ẹ̀yà, àti àwọn iṣẹ́. Wá lẹ́yìn ìforígílé fún \$4.99.',
      'complete_setup': 'Parí Ìṣètò',
      'tap_add_photo': 'Tẹ̀ lé láti fi àwòrán kún',
      'please_enter_name': 'Jọ̀wọ́ tẹ orúkọ tí yóò hàn rẹ',
      'please_enter_username': 'Jọ̀wọ́ tẹ orúkọ aṣàmúlò tó tọ́',
      'username_taken': 'Orúkọ aṣàmúlò yìí ti jẹ́ gbà',
      'username_short': 'Orúkọ aṣàmúlò gbọ́dọ̀ jẹ́ lẹ́tà 3 tàbí jù bẹ́ẹ̀ lọ',
      'username_invalid': 'Lẹ́tà, nọ́mbà, àti àmì ìsàlẹ̀ nìkan ni a gbà láyè',
      'camera': 'Kámẹ́rà',
      'gallery': 'Ilé Àwòrán',
      
      'chats': 'ÌTÀKURỌ̀SỌ̀',
      'status': 'IPÒ',
      'calls': 'ÌPÈ',
      'no_chats': 'Kò sí ìtàkurọ̀sọ̀ láti ìgbà yìí',
      'start_conversation': 'Bẹ̀rẹ̀ ìtàkurọ̀sọ̀ tuntun!',
      'call_history': 'Ìtàn ìpè',
      'status_updates': 'Àwọn ìmúdójú ìpò',
      
      'new_chat': 'Ìtàkurọ̀sọ̀ Tuntun',
      'new_group': 'Ẹgbẹ́ Tuntun',
      'new_channel': 'Ìbòsí Tuntun',
      'video': 'Fidio',
      'text_status': 'Ipò Ọ̀rọ̀',
      'new_call': 'Ìpè Tuntun',
      'video_call': 'Ìpè Fidio',
      'share_code': 'Pín kóòdù yìí pẹ̀lú ẹni tí o fẹ́ pè:',
      
      'settings': 'Ètò',
      'profile': 'Àwòrán',
      'sign_out': 'Jáde',
      
      'account': 'Àkáòwò',
      'security_change_number': 'Ààbò, yí nọ́mbà padà',
      'privacy': 'Àṣírí',
      'block_contacts': 'Dínà àwọn olùbáaṣepọ̀, àwọn ìròyìn tó ń lọ',
      'avatar': 'Àwòrán',
      'create_edit_photo': 'Ṣẹ̀dá, ṣàtúnṣe, àwòrán prófáìlì',
      'theme_wallpapers': 'Àkọlé, àwòrán bàckgráùnd, ìtàn',
      'notifications': 'Àlàrtì',
      'message_group_call_tones': 'Ohùn ìròyìn, ẹgbẹ́ & ìpè',
      'storage_and_data': 'Ibi ipamọ̀ àti Dátà',
      'network_usage': 'Lò nẹ́twọ́kì, ìgbàsílẹ̀ fúnrarẹ̀',
      'app_language': 'Èdè App',
      'english_default': 'Yorùbá',
      'help': 'Ìrànlọ́wọ́',
      'help_center': 'Ilé ìrànlọ́wọ́, àbọ̀, òfin àṣírí',
      'invite_friends': 'Pè Àwọn Ọ̀rẹ́',
      'log_out': 'Jáde',
      'version': 'AURA Chat v1.0.0',
      'select_language': 'Yan Èdè',
      'cancel': 'Fagilé',
    },
    
    // Igbo
    'ig': {
      'enter_phone': 'Tinye nọmba ekwentị gị',
      'otp_description': 'AURA ga-ezigharịrị gị paswọọdụ otu oge iji nyochaa nọmba gị.',
      'request_otp': 'Rịọ OTP',
      'phone_hint': 'Nọmba ekwentị',
      'invalid_phone': 'Nọmba ekwentị na-adịghị mma maka obodo a',
      'hide_number_info': 'Ị nwere ike zoro nọmba gị azọ ma e mesịa ndị ọzọ ga-ahụ aha ọrụ gị naanị.',
      'back_to_terms': 'Laghachi na Usoro',
      
      'verify_number': 'Nyochaa nọmba gị',
      'enter_code_sent_to': 'Tinye koodu 6-nọmba e zigara',
      'resend_code_in': 'Zigharịa koodu n\'ime',
      'resend_code': 'Zigharịa Koodu',
      'verify': 'Nyochaa',
      'invalid_otp': 'OTP na-adịghị mma. Biko nwaa ọzọ.',
      
      'setup_profile': 'Hazie profaịlụ gị',
      'setup_description': 'Họrọ ka ndị ọzọ ga-ahụ gị na AURA. Ị nwere ike ịgbanwe nke a mgbe ọ bụla.',
      'display_name': 'Aha Ngosi',
      'display_name_hint': 'Ka ị chọrọ ka a mara gị',
      'username': 'Aha ọrụ',
      'username_hint': 'Aha ọrụ pụrụ iche gị @',
      'bio': 'Akụkọ',
      'bio_hint': 'Gwa ndị mmadụ gbasara gị',
      'verification': 'Nkwenye',
      'verification_desc': 'Akwụkwọ nkwenye dị maka ndị ọkà mmụta, akara ahịa na azụmahịa. Rịọ ma e mesịa maka \$4.99.',
      'complete_setup': 'Mechie Nhazi',
      'tap_add_photo': 'Pịa iji tinye foto',
      'please_enter_name': 'Biko tinye aha ngosi gị',
      'please_enter_username': 'Biko tinye aha ọrụ ziri ezi',
      'username_taken': 'Aha ọrụ a ewerela',
      'username_short': 'Aha ọrụ kwesịghị ịbụ mkpụrụ edemede 3 ma ọ bụ karịa',
      'username_invalid': 'Naanị mkpụrụ edemede, nọmba na akara underscore ka e kwenyere',
      'camera': 'Kamera',
      'gallery': 'Ọba foto',
      
      'chats': 'MKPARỊTAỤKA',
      'status': 'ỌNỌDỤ',
      'calls': 'OKU',
      'no_chats': 'Enweghị mkparịtaụka ugbu a',
      'start_conversation': 'Bido mkparịtaụka ọhụrụ!',
      'call_history': 'Akụkọ oku',
      'status_updates': 'Mmelite ọnwụnwa',
      
      'new_chat': 'Mkparịtaụka Ọhụrụ',
      'new_group': 'Otu Ọhụrụ',
      'new_channel': 'Ọwa Ọhụrụ',
      'video': 'Vidio',
      'text_status': 'Ọnọdụ Edemede',
      'new_call': 'Oku Ọhụrụ',
      'video_call': 'Oku Vidio',
      'share_code': 'Kekọrịta koodu a na onye ị chọrọ ịkụ:',
      
      'settings': 'Ntọala',
      'profile': 'Profaịlụ',
      'sign_out': 'Pụọ',
      
      'account': 'Akaụntụ',
      'security_change_number': 'Nchebe, ịgbanwe nọmba',
      'privacy': 'Nzuzo',
      'block_contacts': 'Gbochie ndị kọntaktị, ozi na-efu',
      'avatar': 'Foto',
      'create_edit_photo': 'Kepụta, dezie, foto profaịlụ',
      'theme_wallpapers': 'Isiokwu, ihe osise, akụkọ',
      'notifications': 'Nziọkwà',
      'message_group_call_tones': 'Ọkwa ozi, òtù & oku',
      'storage_and_data': 'Nchekwa na Data',
      'network_usage': 'Iji netwọk, ibudata onwe',
      'app_language': 'Asụsụ App',
      'english_default': 'Igbo',
      'help': 'Enyemaka',
      'help_center': 'Ụlọ enyemaka, kọntaktị, iwu nzuzo',
      'invite_friends': 'Kpọọ Ndị Enyi',
      'log_out': 'Pụọ',
      'version': 'AURA Chat v1.0.0',
      'select_language': 'Họrọ Asụsụ',
      'cancel': 'Kagbuo',
    },
  };

  static String get(String key) {
    return _translations[currentLanguage]?[key] ?? 
           _translations['en']?[key] ?? 
           key;
  }

  static List<Map<String, String>> get supportedLanguages => [
    {'code': 'en', 'name': 'English'},
    {'code': 'es', 'name': 'Español'},
    {'code': 'fr', 'name': 'Français'},
    {'code': 'ha', 'name': 'Hausa'},
    {'code': 'yo', 'name': 'Yorùbá'},
    {'code': 'ig', 'name': 'Igbo'},
  ];
}
